// Deutsche Texte für Login und Registrierung.
export const deAuthCopy = {
  common: {
    brand: 'Roamly',
    languageLabel: 'Sprache waehlen',
    german: 'Deutsch',
    english: 'English',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    emailPlaceholder: 'name@beispiel.de',
    passwordPlaceholder: 'Mindestens 8 Zeichen',
    passwordHideLabel: 'Passwort ausblenden',
    passwordShowLabel: 'Passwort anzeigen',
  },
  login: {
    ariaBrand: 'Roamly Travel Shop',
    kicker: 'Wähle dein Abenteuer',
    title: 'Willkommen zurück bei Roamly.',
    intro: 'Melde dich an und finde schnell alles für deine nächste Reise.',
    headerKicker: 'Dein Konto',
    heading: 'Anmelden',
    description: 'Mit deinem Konto kannst du weiter einkaufen und deine Bestellungen sehen.',
    submit: 'Anmelden',
    loading: 'Wird geladen...',
    footer: 'Noch kein Roamly Konto?',
    footerLink: 'Jetzt registrieren',
    error: 'E-Mail oder Passwort falsch.',
  },
  register: {
    ariaBrand: 'Roamly Travel Shop',
    kicker: 'Wähle dein Abenteuer',
    title: 'Erstelle dein Roamly Konto.',
    intro: 'Entdecke Produkte für Hiking, Camping und Surfing.',
    headerKicker: 'Neues Konto',
    heading: 'Konto erstellen',
    description: 'Speichere deinen Warenkorb und behalte deine Bestellungen im Blick.',
    confirmPassword: 'Passwort bestätigen',
    confirmPlaceholder: 'Noch einmal eingeben',
    submit: 'Konto erstellen',
    loading: 'Wird registriert...',
    footer: 'Bereits ein Konto?',
    footerLink: 'Jetzt anmelden',
    passwordLabels: ['Noch leer', 'Basis', 'Solide', 'Gut', 'Sehr stark'],
    meterLabel: 'Passwortstärke',
    mismatchHint: 'Passwörter stimmen noch nicht überein.',
    mismatchError: 'Passwörter stimmen nicht überein.',
    shortPasswordError: 'Passwort muss mindestens 8 Zeichen lang sein.',
    conflictError: 'Diese E-Mail ist bereits registriert.',
    defaultError: 'Registrierung fehlgeschlagen. Bitte versuche es erneut.',
  },
} as const;
