// Englische Texte für Login und Registrierung.
export const enAuthCopy = {
  common: {
    brand: 'Roamly',
    languageLabel: 'Choose language',
    german: 'Deutsch',
    english: 'English',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: 'At least 8 characters',
    passwordHideLabel: 'Hide password',
    passwordShowLabel: 'Show password',
  },
  login: {
    ariaBrand: 'Roamly Travel Shop',
    kicker: 'Choose your adventure',
    title: 'Welcome back to Roamly.',
    intro: 'Sign in and quickly find what you need for your next trip.',
    headerKicker: 'Your account',
    heading: 'Sign in',
    description: 'Use your account to keep shopping and see your orders.',
    submit: 'Sign in',
    loading: 'Signing in...',
    footer: 'No Roamly account yet?',
    footerLink: 'Create one now',
    error: 'Email or password is incorrect.',
  },
  register: {
    ariaBrand: 'Roamly Travel Shop',
    kicker: 'Choose your adventure',
    title: 'Create your Roamly account.',
    intro: 'Discover products for hiking, camping, and surfing.',
    headerKicker: 'New account',
    heading: 'Create account',
    description: 'Save your cart and keep your orders easy to find.',
    confirmPassword: 'Confirm password',
    confirmPlaceholder: 'Enter it again',
    submit: 'Create account',
    loading: 'Creating account...',
    footer: 'Already have an account?',
    footerLink: 'Sign in now',
    passwordLabels: ['Empty', 'Basic', 'Solid', 'Good', 'Very strong'],
    meterLabel: 'Password strength',
    mismatchHint: 'Passwords do not match yet.',
    mismatchError: 'Passwords do not match.',
    shortPasswordError: 'Password must be at least 8 characters long.',
    conflictError: 'This email is already registered.',
    defaultError: 'Registration failed. Please try again.',
  },
} as const;
