import type { HomeText } from './home.en';

export const homeDe: HomeText = {
  navLabel: 'Hauptnavigation',
  homeLabel: 'Roamly Startseite',
  home: 'Home',
  shop: 'Shop',
  wishlistLabel: 'Wunschliste öffnen',
  cartLabel: 'Warenkorb öffnen',
  products: 'Alle Produkte',
  categories: 'Kategorien',
  discounts: 'Rabatte',
  about: 'Über uns',
  contacts: 'Kontakt',
  categoryItems: ['Hiking', 'Camping', 'Surfing'],
  accountLabel: 'Kontoseite öffnen',
  logout: 'Abmelden',
  kicker: 'Reise-Shop für jede Route',
  title: 'Plane deinen nächsten Outdoor-Trip mit Roamly.',
  intro: 'Ausrüsten. Aufbrechen. Nicht zurückblicken.',
  createAccount: 'Konto erstellen',
  existingAccount: 'Ich habe schon ein Konto',
  tripCategoriesLabel: 'Ausgewählte Reise-Kategorien',
  highlightsLabel: 'Roamly Vorteile',
  cards: [
    { category: 'Hiking', title: 'Berg-Ausrüstung' },
    { category: 'Camping', title: 'Nacht-Setup' },
    { category: 'Surfing', title: 'Küsten-Set' },
  ],
  highlights: [
    { title: 'Kategorie wählen', text: 'Stöbere in Produkten passend zu deiner Reiseart.' },
    { title: 'Warenkorb speichern', text: 'Registriere dich einmal und plane später weiter.' },
    { title: 'Bestellungen verfolgen', text: 'Behalte dein Konto und Käufe an einem Ort.' },
  ],
};
