import type { HomeText } from './home.en';

export const homeDe: HomeText = {
  navLabel: 'Hauptnavigation',
  homeLabel: 'Roamly Startseite',
  home: 'Home',
  shop: 'Shop',
  searchLabel: 'Produkte suchen',
  searchPlaceholder: 'Suchen…',
  closeSearchLabel: 'Suche schließen',
  wishlistLabel: 'Wunschliste öffnen',
  cartLabel: 'Warenkorb öffnen',
  products: 'Alle Produkte',
  categories: 'Kategorien',
  discounts: 'Rabatte',
  about: 'Über uns',
  contacts: 'Kontakt',
  categoryItems: ['Hiking', 'Camping', 'Surfing'],
  accountLabel: 'Kontoseite öffnen',
  logout: 'Abmelden',
  title: 'Plane deinen nächsten Outdoor-Trip mit Roamly.',
  intro: 'Ausrüsten. Aufbrechen. Nicht zurückblicken.',
  createAccount: 'Konto erstellen',
  existingAccount: 'Ich habe schon ein Konto',
  tripCategoriesLabel: 'Ausgewählte Reise-Kategorien',
  cards: [
    { category: 'Hiking', title: 'Berg-Ausrüstung' },
    { category: 'Camping', title: 'Nacht-Setup' },
    { category: 'Surfing', title: 'Küsten-Set' },
  ],
  featuredKicker: 'Unsere Top-Picks',
  featuredTitle: 'Diese Woche beliebt',
  reviewsKicker: 'Kundenstimmen',
  reviewsTitle: 'Was andere sagen',
  reviews: [
    {
      text: 'Den Rucksack habe ich auf einer Dreitagestour in den Dolomiten getragen. Null Beschwerden – der Hüftgurt saß die ganze Zeit perfekt.',
      name: 'Sarah M.',
      productLabel: 'Trailhead 38L Rucksack',
      productId: 'trailhead-pack-38',
    },
    {
      text: 'Das Zelt stand in unter zehn Minuten, trotz Regen. Solide Ausrüstung – für den Preis absolut überzeugend.',
      name: 'Tom K.',
      productLabel: 'Ultralight 2-Personen Zelt',
      productId: 'ultralight-tent-2p',
    },
    {
      text: 'Hält mich in der Ostsee im Oktober warm. Ich war wirklich überrascht, wie beweglich der Anzug ist.',
      name: 'Lena W.',
      productLabel: '4/3 Steamer Wetsuit',
      productId: 'steamer-43-wetsuit',
    },
  ],
};
