import type { AccountText } from './account.en';

export const accountDe: AccountText = {
  kicker: 'Persoenlicher Bereich',
  title: 'Dein Roamly Konto',
  intro: 'Verwalte dein Profil, deinen Warenkorb und spaetere Bestellungen an einem Ort.',
  profileLabel: 'Profildaten',
  nameLabel: 'Name',
  emailLabel: 'E-Mail',
  roleLabel: 'Kontotyp',
  fallbackName: 'Roamly Kunde',
  fallbackEmail: 'Keine E-Mail gespeichert',
  actionsLabel: 'Konto-Aktionen',
  savedTripsLabel: 'Gespeicherte Reisen',
  activeOrdersLabel: 'Aktive Bestellungen',
  bonusPointsLabel: 'Roamly Punkte',
  cartTitle: 'Warenkorb',
  cartText: 'Pruefe die Ausruestung, die du fuer deine naechste Reise gespeichert hast.',
  cartLink: 'Warenkorb oeffnen',
  shopTitle: 'Shop',
  shopText: 'Stoeber weiter in Hiking-, Camping- und Surfing-Produkten.',
  shopLink: 'Produkte ansehen',
  supportTitle: 'Support',
  supportText: 'Stelle eine Frage zu Konto, Lieferung oder Rueckgabe.',
  supportLink: 'Kontakt oeffnen',
  tripKicker: 'Naechster Reiseplan',
  tripTitle: 'Wochenendroute in den Bergen',
  tripText: 'Ein kompakter Plan fuer zwei Tage Hiking mit leichtem Camping-Setup und wetterfester Kleidung.',
  tripDateLabel: 'Datum',
  tripDate: '28. - 29. Juni',
  tripGearLabel: 'Ausrustung',
  tripGear: 'Rucksack, Shell-Jacke, Camp-Laterne',
  tripRouteLabel: 'Route',
  tripRoute: 'Alpine Route und See-Camp',
  ordersKicker: 'Letzte Aktivitaet',
  ordersTitle: 'Bestellungen und gespeicherte Plaene',
  orders: [
    {
      id: 'RM-2048',
      title: 'Alpine Trail Rucksack',
      meta: 'Im Warenkorb reserviert',
      status: 'Wartet',
    },
    {
      id: 'RM-2031',
      title: 'Basecamp Setup',
      meta: 'Camping-Kollektion gespeichert',
      status: 'Gespeichert',
    },
    {
      id: 'RM-1984',
      title: 'Coast Kit Checkliste',
      meta: 'Surfing-Ausrustungsliste',
      status: 'Geplant',
    },
  ],
  logout: 'Abmelden',
};
