import type { ProductText } from './products.en';

export const productsDe: ProductText = {
  navLabel: 'Produktnavigation',
  kicker: 'Roamly Shop',
  title: 'Ausrüstung für Hiking, Camping und Surfing.',
  intro: 'Wähle komplette Outdoor-Basics für deine nächste Route.',
  allProducts: 'Alle Produkte',
  allCategories: 'Alle',
  categoryFilterLabel: 'Kategorie',
  collectionDescriptions: {
    all: 'Alles für die Route',
    hiking: 'Leichte Layer und Packs',
    camping: 'Schutz, Licht und Komfort',
    surfing: 'Basics für das Wasser',
  },
  filtersLabel: 'Produktfilter',
  noResults: 'Keine Produkte passen zu diesen Filtern.',
  resultsCount: (count) => `${count} ${count === 1 ? 'Produkt' : 'Produkte'} gefunden`,
  searchLabel: 'Suche',
  searchPlaceholder: 'Ausrüstung suchen…',
  sortLabel: 'Sortieren nach',
  sortOptions: {
    featured: 'Empfohlen',
    priceAsc: 'Niedrigster Preis',
    ratingDesc: 'Beste Bewertung',
  },
  viewProduct: 'Ansehen',
  addToCart: 'In den Warenkorb',
  saveToWishlist: 'Auf Wunschliste',
  savedToWishlist: 'Von Wunschliste entfernen',
  categoryLabel: 'Kategorie',
  priceLabel: 'Preis',
  priceUpTo: (max) => `Bis ${max} EUR`,
  priceAny: 'Beliebiger Preis',
  ratingLabel: 'Bewertung',
  ratingAny: 'Beliebig',
  resetFilters: 'Filter zurücksetzen',
  detailsLabel: 'Ausstattung',
  backToProducts: 'Zurück zu Produkten',
  notFoundTitle: 'Produkt nicht gefunden',
  notFoundText: 'Dieses Produkt ist nicht mehr im Sortiment.',
  quantityLabel: 'Menge',
  relatedLabel: 'Mehr aus dieser Kategorie',
  trustShipping: 'Kostenloser Versand ab 80 EUR',
  trustReturns: 'Kostenlose Rücksendung innerhalb von 30 Tagen',
  trustWarranty: '2 Jahre Garantie auf alle Produkte',
  reviewsTitle: 'Kundenbewertungen',
  reviewsCount: (n) => `${n} ${n === 1 ? 'Bewertung' : 'Bewertungen'}`,
  reviewsEmpty: 'Noch keine Bewertungen — sei der Erste!',
  writeReviewTitle: 'Bewertung schreiben',
  reviewNameLabel: 'Dein Name',
  reviewNamePlaceholder: 'z. B. Anna M.',
  reviewTextLabel: 'Deine Bewertung',
  reviewTextPlaceholder: 'Was denkst du über dieses Produkt?',
  reviewSubmit: 'Bewertung absenden',
  reviewThanks: 'Danke für deine Bewertung!',
  reviewRatingLabel: 'Deine Bewertung',
  categories: {
    hiking: 'Hiking',
    camping: 'Camping',
    surfing: 'Surfing',
  },
};
