import type { ProductText } from './products.en';

export const productsDe: ProductText = {
  navLabel: 'Produktnavigation',
  kicker: 'Roamly Shop',
  title: 'Ausrüstung für Hiking, Camping und Surfing.',
  intro: 'Wähle komplette Outdoor-Basics für deine nächste Route.',
  allProducts: 'Alle Produkte',
  allCategories: 'Alle',
  categoryFilterLabel: 'Produkte nach Kategorie filtern',
  collectionDescriptions: {
    all: 'Alles für die Route',
    hiking: 'Leichte Layer und Packs',
    camping: 'Schutz, Licht und Komfort',
    surfing: 'Basics für das Wasser',
  },
  filtersLabel: 'Produktfilter',
  noResults: 'Keine Produkte passen zu diesen Filtern.',
  resultsCount: (count) => `${count} ${count === 1 ? 'Produkt' : 'Produkte'} angezeigt`,
  searchLabel: 'Suche',
  searchPlaceholder: 'Ausrüstung suchen',
  sortLabel: 'Sortieren nach',
  sortOptions: {
    featured: 'Empfohlen',
    priceAsc: 'Niedrigster Preis',
    ratingDesc: 'Beste Bewertung',
  },
  viewProduct: 'Produkt ansehen',
  addToCart: 'In den Warenkorb',
  categoryLabel: 'Kategorie',
  priceLabel: 'Preis',
  ratingLabel: 'Bewertung',
  detailsLabel: 'Ausstattung',
  backToProducts: 'Zurück zu Produkten',
  notFoundTitle: 'Produkt nicht gefunden',
  notFoundText: 'Dieses Produkt ist nicht mehr im Sortiment.',
  categories: {
    hiking: 'Hiking',
    camping: 'Camping',
    surfing: 'Surfing',
  },
};
